# BOT-KONFIGURATION
[bot]
server: localhost
# Die Adresse des Moonraker-Servers. Standard ist localhost
port: 7125
# Die Portnummer des Moonraker-Servers. Standard ist 7125
chat_id: 000000000
# Die Chat-ID für die Kommunikation mit dem Bot. Erhalten Sie diese über den BotFather oder andere Bots.
bot_token: 000000000:000000000000000000000000000
# Das Token für den Zugriff auf die HTTP-API des Bots. Erhalten Sie dieses vom BotFather.
# log_path: /home/pi/klipper_logs
# Pfad zum Verzeichnis für die Log-Dateien des Bots. Standardmäßig im Home-Verzeichnis.

[camera]
host: http://localhost:8080/?action=snapshot
# Die URL für den Abruf von Schnappschüssen der Kamera.
fps: 30
# Bilder pro Sekunde für den Videostream (falls unterstützt).
flip_vertically: false
# Das Bild vertikal spiegeln. Standard ist false.
flip_horizontally: false
# Das Bild horizontal spiegeln. Standard ist false.
rotate: 0
# Das Bild drehen (0, 90, 180, 270 Grad).
video_duration: 5
# Dauer der Videoaufnahme in Sekunden.

[progress_notification]
# percent: 5
# Benachrichtigungsintervall basierend auf dem Fortschritt in Prozent.
# height: 5
# Benachrichtigungsintervall basierend auf der Druckhöhe in mm.
# time: 600
# Benachrichtigungsintervall basierend auf der Zeit in Sekunden.

[status_message_content]
# Hier können Sie festlegen, welche Informationen in den Statusmeldungen enthalten sein sollen.
content: progress, height, filament_length, time_left, eta, finish_time, m117_status, tg_notify_status, last_update_time
# Mögliche Werte: progress, height, filament_length, time_left, eta, finish_time, m117_status, tg_notify_status, last_update_time

[telegram_ui]
# Einstellungen für die Benutzeroberfläche in Telegram.
# silent_progress: true
# Fortschrittsmeldungen ohne Ton senden.
# silent_commands: true
# Bestätigungen für Befehle ohne Ton senden.
# silent_status: true
# Statusmeldungen ohne Ton senden.
# include_snapshot: true
# Schnappschuss in Statusmeldungen einfügen.

[custom_commands]
# Definieren Sie hier eigene Befehle für den Bot.
# Beispiel:
# menu_name: Befehl_an_Klipper
